version: '3.8'

services:
  app:
    image: nullstone/node:local
    command: npm run dev
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    environment:
      - NODE_ENV=development
